#!/usr/bin/env python3
"""
Aegis Hub — operator landing page + narrowly scoped certificate/domain control.

Privilege model (operator requirement, 2026-09-24):
  * The main Caddyfile is console-only (root, 0600, mounted read-only here).
  * This service may ONLY write /etc/caddy/sites-enabled/domain.caddy, generated from the
    fixed TEMPLATE below with a validated hostname. It cannot add, remove, or change any
    other directive. Gateway/proxy changes require the console.
  * It reaches Caddy's admin API only because it shares Caddy's network namespace
    (compose: network_mode: service:caddy). No other container can.
  * Reachable only via Caddy at /hub, behind basic-auth enforced at the edge.

Stdlib only — no pip, no build step, small audit surface.
"""
from __future__ import annotations

import html
import json
import os
import re
import socket
import ssl
import sys
import time
import urllib.request
from datetime import datetime, timezone
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from urllib.parse import parse_qs, urlparse

CADDYFILE = "/etc/caddy/Caddyfile"
SITES_DIR = "/etc/caddy/sites-enabled"
DOMAIN_FILE = os.path.join(SITES_DIR, "domain.caddy")
ADMIN = "http://localhost:2019"
LAN_IP = os.environ.get("AEGIS_LAN_IP", "127.0.0.1")
AUDIT = "/app/audit/hub-audit.jsonl"

HOSTNAME_RE = re.compile(r"^(?=.{1,253}$)(?!-)([a-z0-9-]{1,63}(?<!-)\.)+[a-z]{2,63}$")

TEMPLATE = """# GENERATED BY AEGIS HUB {ts} — do not hand-edit; regenerate from /hub or delete on the console.
{hostname} {{
    import site
}}
"""

SERVICES = [
    ("Open WebUI", "/", "live", "Chat, documents, benchmarks — routed through LiteLLM + VetoGuard"),
    ("Grafana", "/grafana/", "optional", "GPU / host telemetry (docker-compose.monitoring.yml)"),
    ("Fish Speech", None, "planned", "TTS — requires GPU assignment decision (console)"),
    ("ComfyUI", None, "planned", "Image generation — blocked until two-stage safety gate exists"),
]


def audit(event: str, **fields) -> None:
    rec = {"ts": datetime.now(timezone.utc).isoformat(), "event": event, **fields}
    try:
        with open(AUDIT, "a", encoding="utf-8") as f:
            f.write(json.dumps(rec) + "\n")
    except OSError as e:  # never fail a request because the audit dir is missing
        print(f"audit write failed: {e}", file=sys.stderr)


# ---------------------------------------------------------------------------
# Certificate inspection
# ---------------------------------------------------------------------------
def probe_cert(host: str, sni: str | None = None, port: int = 443) -> dict:
    ctx = ssl.create_default_context()
    ctx.check_hostname = False
    ctx.verify_mode = ssl.CERT_NONE
    try:
        with socket.create_connection((host, port), timeout=5) as s:
            with ctx.wrap_socket(s, server_hostname=sni or host) as tls:
                der = tls.getpeercert(binary_form=True)
                cert = ssl.DER_cert_to_PEM_cert(der)
                info = ssl._ssl._test_decode_cert  # type: ignore[attr-defined]
    except Exception as e:  # noqa: BLE001
        return {"host": host, "error": str(e)}
    # Decode via a temp file: the stdlib only exposes cert decoding by path.
    import tempfile
    with tempfile.NamedTemporaryFile("w", suffix=".pem", delete=False) as f:
        f.write(cert)
        path = f.name
    try:
        d = info(path)
    finally:
        os.unlink(path)
    exp = datetime.strptime(d["notAfter"], "%b %d %H:%M:%S %Y %Z").replace(tzinfo=timezone.utc)
    return {
        "host": host,
        "subject": dict(x[0] for x in d.get("subject", ())),
        "issuer": dict(x[0] for x in d.get("issuer", ())),
        "san": [v for k, v in d.get("subjectAltName", ()) if k == "DNS"],
        "not_before": d["notBefore"],
        "not_after": d["notAfter"],
        "days_remaining": round((exp - datetime.now(timezone.utc)).total_seconds() / 86400, 1),
    }


def current_domain() -> str | None:
    try:
        with open(DOMAIN_FILE, encoding="utf-8") as f:
            for line in f:
                m = re.match(r"^([a-z0-9.-]+) \{$", line.strip())
                if m:
                    return m.group(1)
    except FileNotFoundError:
        return None
    return None


def caddy_reload() -> tuple[bool, str]:
    """Re-adapt the read-only Caddyfile (which imports sites-enabled/*) and load it."""
    with open(CADDYFILE, "rb") as f:
        body = f.read()
    req = urllib.request.Request(
        f"{ADMIN}/load", data=body, method="POST",
        headers={"Content-Type": "text/caddyfile", "Origin": "localhost:2019"},
    )
    try:
        with urllib.request.urlopen(req, timeout=15) as r:
            return True, f"caddy reload ok ({r.status})"
    except urllib.error.HTTPError as e:
        return False, f"caddy rejected config: {e.read().decode(errors='replace')[:500]}"
    except Exception as e:  # noqa: BLE001
        return False, f"caddy admin unreachable: {e}"


# ---------------------------------------------------------------------------
# HTTP
# ---------------------------------------------------------------------------
PAGE = """<!doctype html><meta charset=utf-8><title>Aegis Hub</title>
<style>
body{{font:15px/1.5 system-ui,sans-serif;max-width:880px;margin:2rem auto;padding:0 1rem;color:#1a1a1a;background:#fafafa}}
h1{{font-weight:600}} .grid{{display:grid;grid-template-columns:repeat(auto-fill,minmax(240px,1fr));gap:1rem}}
.card{{border:1px solid #ddd;border-radius:8px;padding:1rem;background:#fff}} .tag{{font-size:12px;padding:2px 8px;border-radius:999px;background:#eee}}
.live{{background:#d9f5dd}} .planned{{background:#f3e7c9}} .optional{{background:#dfe9f7}}
table{{border-collapse:collapse;width:100%}} td,th{{text-align:left;padding:4px 8px;border-bottom:1px solid #eee;font-size:14px}}
form{{margin-top:1rem}} input{{padding:6px;font-size:14px;width:260px}} button{{padding:6px 12px}} .warn{{color:#a33}} .ok{{color:#2a7}}
code{{background:#eee;padding:1px 4px;border-radius:3px}} .note{{font-size:13px;color:#555}}
</style>
<h1>Aegis Hub</h1>
<div class=grid>{cards}</div>
<h2>TLS certificates</h2>
<table><tr><th>Endpoint</th><th>Issuer</th><th>Expires</th><th>Days left</th></tr>{certrows}</table>
<h2>Public hostname (Let's Encrypt)</h2>
<p class=note>Current: <code>{domain}</code>. Writes only <code>sites-enabled/domain.caddy</code> from a fixed template, then reloads Caddy.
HTTP-01 needs the firewall to forward 80/443 to this host. Gateway/proxy configuration is console-only.</p>
<form method=post action=/hub/domain>
  <input name=hostname placeholder="ai.example.com" value="{domain_val}" pattern="[a-z0-9.-]+" required>
  <button name=action value=apply>Apply / re-apply</button>
  <button name=action value=remove formnovalidate>Remove</button>
</form>
<p class="{msgcls}">{msg}</p>
<p class=note>Audit log: <code>proxy/audit/hub-audit.jsonl</code> on the host.</p>
"""


class Handler(BaseHTTPRequestHandler):
    server_version = "AegisHub/1"

    def log_message(self, fmt, *args):  # quiet; Caddy has the access log
        pass

    def _send(self, code: int, body: str, ctype="text/html; charset=utf-8"):
        data = body.encode()
        self.send_response(code)
        self.send_header("Content-Type", ctype)
        self.send_header("Content-Length", str(len(data)))
        self.send_header("Cache-Control", "no-store")
        self.end_headers()
        self.wfile.write(data)

    def _page(self, msg="", ok=True):
        dom = current_domain()
        cards = "".join(
            f'<div class=card><b>{html.escape(n)}</b> <span class="tag {s}">{s}</span><p class=note>{html.escape(d)}</p>'
            + (f'<a href="{u}">open</a>' if u else "") + "</div>"
            for n, u, s, d in SERVICES
        )
        rows = []
        for host, sni in [(LAN_IP, None)] + ([(LAN_IP, dom)] if dom else []):
            c = probe_cert(host, sni)
            if "error" in c:
                rows.append(f"<tr><td>{html.escape(sni or host)}</td><td colspan=3 class=warn>{html.escape(c['error'])}</td></tr>")
            else:
                iss = c["issuer"].get("commonName") or c["issuer"].get("organizationName", "?")
                cls = "warn" if c["days_remaining"] < 14 else "ok"
                rows.append(f"<tr><td>{html.escape(sni or host)}</td><td>{html.escape(iss)}</td><td>{c['not_after']}</td><td class={cls}>{c['days_remaining']}</td></tr>")
        return PAGE.format(cards=cards, certrows="".join(rows), domain=html.escape(dom or "none"),
                           domain_val=html.escape(dom or ""), msg=html.escape(msg), msgcls="ok" if ok else "warn")

    def do_GET(self):
        p = urlparse(self.path).path
        if p in ("/hub", "/hub/"):
            return self._send(200, self._page())
        if p == "/hub/api/status":
            dom = current_domain()
            out = {"lan": probe_cert(LAN_IP), "domain": dom, "public": probe_cert(LAN_IP, dom) if dom else None,
                   "services": [{"name": n, "url": u, "state": s} for n, u, s, _ in SERVICES]}
            return self._send(200, json.dumps(out, indent=1), "application/json")
        self._send(404, "not found", "text/plain")

    def do_POST(self):
        p = urlparse(self.path).path
        if p != "/hub/domain":
            return self._send(404, "not found", "text/plain")
        n = int(self.headers.get("Content-Length", "0"))
        form = parse_qs(self.rfile.read(min(n, 4096)).decode())
        action = form.get("action", [""])[0]
        hostname = form.get("hostname", [""])[0].strip().lower()
        if action == "remove":
            try:
                os.unlink(DOMAIN_FILE)
            except FileNotFoundError:
                pass
            ok, msg = caddy_reload()
            audit("domain_remove", ok=ok, detail=msg)
            return self._send(200, self._page(f"Removed public hostname. {msg}", ok))
        if action != "apply" or not HOSTNAME_RE.match(hostname):
            audit("domain_reject", hostname=hostname)
            return self._send(400, self._page("Rejected: hostname must be a valid public DNS name.", False))
        content = TEMPLATE.format(ts=datetime.now(timezone.utc).isoformat(timespec="seconds"), hostname=hostname)
        tmp = DOMAIN_FILE + ".tmp"
        with open(tmp, "w", encoding="utf-8") as f:
            f.write(content)
        os.replace(tmp, DOMAIN_FILE)
        ok, msg = caddy_reload()
        if not ok:  # roll back so a bad hostname cannot leave Caddy in a failed state
            os.unlink(DOMAIN_FILE)
            caddy_reload()
        audit("domain_apply", hostname=hostname, ok=ok, detail=msg)
        return self._send(200 if ok else 502, self._page(
            f"Applied {hostname}. Caddy will obtain a certificate once DNS resolves here and 80/443 are reachable. {msg}"
            if ok else f"Failed and rolled back: {msg}", ok))


if __name__ == "__main__":
    os.makedirs(SITES_DIR, exist_ok=True)
    ThreadingHTTPServer(("127.0.0.1", 9000), Handler).serve_forever()
