#!/usr/bin/env python3
"""
Aegis Hub v2 — admin control centre. Stdlib only.

Reachable only through Caddy at /hub behind basic-auth (the "administrator"). Shares Caddy's network
namespace, so it can talk to: Caddy admin (localhost:2019), LiteLLM (edge), Ollama (backend, read +
delete), modeld (mgmt, pulls). Every state change is appended to /app/audit/hub-audit.jsonl and, if a
webhook is configured, alerted.

What the hub may change            What it may only VIEW (isolation layer — console-only)
  VetoGuard policy (categories,       caddy/Caddyfile (routes, auth, headers, interconnects)
    guard model, tripwires)           docker-compose.yml (networks, mounts, capabilities)
  Models: pull / remove / expose
  API keys: mint / revoke
  Public hostname + Cloudflare token (one templated site file)
  Alert webhook
Hard rules enforced here regardless of UI: S4 cannot be unblocked; guard models cannot be exposed;
the classifier cannot be disabled; fail-closed cannot be disabled.
"""
from __future__ import annotations

import html
import json
import os
import re
import secrets
import socket
import ssl
import sys
import threading
import urllib.error
import urllib.parse
import urllib.request
from datetime import datetime, timezone
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer

# ---------------------------------------------------------------- config / paths ----------
LAN_IP = os.environ.get("AEGIS_LAN_IP", "127.0.0.1")
MASTER_KEY = os.environ.get("LITELLM_MASTER_KEY", "")
GRAFANA_ENABLED = os.environ.get("GRAFANA_ENABLED", "0") == "1"
CADDYFILE = "/etc/caddy/Caddyfile"
COMPOSE_VIEW = "/app/view/docker-compose.yml"
SITES_DIR = "/etc/caddy/sites-enabled"
DOMAIN_FILE = os.path.join(SITES_DIR, "domain.caddy")
HUB_AUTH_FILE = os.path.join(SITES_DIR, "hub-auth.conf")
POLICY_FILE = "/app/policy/veto-policy.json"
STATE_FILE = "/app/state/hub.json"
AUDIT_DIR = "/app/audit"
HUB_AUDIT = os.path.join(AUDIT_DIR, "hub-audit.jsonl")
VETO_AUDIT = os.path.join(AUDIT_DIR, "veto-audit.jsonl")
CADDY_ADMIN = "http://127.0.0.1:2019"
LITELLM = "http://litellm:4000"
OLLAMA = "http://ollama:11434"
MODELD = "http://modeld:11434"
CSRF = secrets.token_urlsafe(24)

HOSTNAME_RE = re.compile(r"^(?=.{1,253}$)(?!-)([a-z0-9-]{1,63}(?<!-)\.)+[a-z]{2,63}$")
CF_TOKEN_RE = re.compile(r"^[A-Za-z0-9_-]{30,80}$")
MODEL_RE = re.compile(r"^[a-z0-9][a-z0-9._/-]{0,120}(:[a-z0-9._-]{1,60})?$")
ALIAS_RE = re.compile(r"^[a-z0-9][a-z0-9._-]{1,40}$")

CATEGORIES = {
    "S1": ("Violent crimes", "illegal"), "S2": ("Non-violent crimes", "illegal"), "S3": ("Sex-related crimes", "illegal"),
    "S4": ("Child sexual exploitation", "locked"), "S5": ("Defamation", "adult/legal"), "S6": ("Specialized advice", "adult/legal"),
    "S7": ("Privacy", "adult/legal"), "S8": ("Intellectual property", "adult/legal"), "S9": ("Indiscriminate weapons", "illegal"),
    "S10": ("Hate (protected classes)", "protected"), "S11": ("Suicide & self-harm", "protected"), "S12": ("Sexual content (adult)", "adult/legal"),
    "S13": ("Elections", "adult/legal"), "S14": ("Code interpreter abuse", "adult/legal"),
}
DEFAULT_BLOCK = {"S1", "S2", "S3", "S4", "S9", "S10", "S11"}
DEFAULT_POLICY = {"guard": {"model": "llama-guard3:1b", "chunk_chars": 6000, "max_chunks": 200, "timeout": 60},
                  "categories": {c: {"block": c in DEFAULT_BLOCK} for c in CATEGORIES},
                  "tripwires": {"enabled": True, "extra_patterns": []}, "updated": None, "updated_by": None}

DOMAIN_TEMPLATE = """# GENERATED BY AEGIS HUB {ts} — regenerate from /hub or delete on the console. Do not hand-edit.
{hostname} {{
    tls {{
        dns cloudflare {token}
    }}
    import site
}}
"""

NAV = [
    ("overview", "Overview", [("dashboard", "Dashboard"), ("services", "Services")]),
    ("safety", "Safety", [("policy", "VetoGuard policy"), ("audit", "Audit log"), ("alerts", "Alerts")]),
    ("models", "Models", [("installed", "Installed"), ("pull", "Pull"), ("exposed", "Exposed to apps")]),
    ("access", "Access", [("keys", "API keys"), ("password", "Admin password")]),
    ("gateway", "Gateway", [("certs", "Certificates"), ("hostname", "Public hostname"), ("isolation", "Isolation (read-only)")]),
]

JOBS: dict[str, dict] = {}
JOBS_LOCK = threading.Lock()
REQ = threading.local()          # per-request: REQ.q (query dict), REQ.path
PAGE_SIZES = (10, 25, 50, 100)


# ---------------------------------------------------------------- utilities ----------------
def now() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def esc(s) -> str:
    return html.escape(str(s if s is not None else ""))


def load_json(path, default):
    try:
        with open(path, encoding="utf-8") as f:
            return json.load(f)
    except (OSError, ValueError):
        return default


def save_json(path, data) -> None:
    tmp = path + ".tmp"
    with open(tmp, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=1)
    os.chmod(tmp, 0o600)
    os.replace(tmp, path)


def state() -> dict:
    return load_json(STATE_FILE, {"webhook": "", "hostname": ""})


def http(method, url, body=None, headers=None, timeout=15):
    """Return (status, parsed-json-or-text). Never raises."""
    data = json.dumps(body).encode() if isinstance(body, (dict, list)) else (body.encode() if isinstance(body, str) else body)
    h = {"Content-Type": "application/json", **(headers or {})}
    req = urllib.request.Request(url, data=data, method=method, headers=h)
    try:
        with urllib.request.urlopen(req, timeout=timeout) as r:
            raw = r.read().decode(errors="replace")
            st = r.status
    except urllib.error.HTTPError as e:
        raw, st = e.read().decode(errors="replace"), e.code
    except Exception as e:  # noqa: BLE001
        return 0, str(e)
    try:
        return st, json.loads(raw)
    except ValueError:
        return st, raw


def litellm(method, path, body=None):
    return http(method, LITELLM + path, body, {"Authorization": f"Bearer {MASTER_KEY}"}, timeout=30)


def audit(event: str, **fields) -> None:
    rec = {"ts": now(), "actor": "admin", "event": event, **fields}
    try:
        os.makedirs(AUDIT_DIR, exist_ok=True)
        with open(HUB_AUDIT, "a", encoding="utf-8") as f:
            f.write(json.dumps(rec) + "\n")
    except OSError as e:
        print(f"audit write failed: {e}", file=sys.stderr)
    alert(f"[aegis-hub] {event}: " + ", ".join(f"{k}={v}" for k, v in fields.items() if k not in ("token",)))


def alert(text: str) -> None:
    url = state().get("webhook", "")
    if not url:
        return
    def _send():
        http("POST", url, {"text": text, "content": text, "source": "aegis-hub", "ts": now()}, timeout=5)
    threading.Thread(target=_send, daemon=True).start()


def tail_jsonl(path, n=200):
    try:
        with open(path, encoding="utf-8") as f:
            lines = f.readlines()[-n:]
    except OSError:
        return []
    out = []
    for l in reversed(lines):
        try:
            out.append(json.loads(l))
        except ValueError:
            continue
    return out



def q(key, default=""):
    return getattr(REQ, "q", {}).get(key, [default])[0]


def paginate(rows, key, default_per=25):
    """Slice rows for table `key` using ?<key>_per=&<key>_page=; returns (page_rows, controls_html)."""
    try: per = int(q(f"{key}_per", default_per))
    except ValueError: per = default_per
    per = per if per in PAGE_SIZES else default_per
    total = len(rows); pages = max(1, (total + per - 1) // per)
    try: pg = min(max(1, int(q(f"{key}_page", 1))), pages)
    except ValueError: pg = 1
    path = getattr(REQ, "path", "/hub")
    other = {k: v[0] for k, v in getattr(REQ, "q", {}).items() if not k.startswith(key + "_")}
    def link(p, n):
        params = {**other, f"{key}_per": str(n), f"{key}_page": str(p)}
        return path + "?" + urllib.parse.urlencode(params)
    sizes = " ".join(f'<a href="{link(1, n)}"{" class=on" if n == per else ""}>{n}</a>' for n in PAGE_SIZES)
    prev = f'<a href="{link(pg - 1, per)}">&larr; prev</a>' if pg > 1 else '<span class="mut">&larr; prev</span>'
    nxt = f'<a href="{link(pg + 1, per)}">next &rarr;</a>' if pg < pages else '<span class="mut">next &rarr;</span>'
    ctl = f'<div class="pager"><span>per page: {sizes}</span><span>{prev} &nbsp; page {pg} / {pages} &nbsp; {nxt}</span><span class="mut">{total} entries</span></div>'
    return rows[(pg - 1) * per: pg * per], ctl


# ---------------------------------------------------------------- domain objects ----------
def policy() -> dict:
    p = load_json(POLICY_FILE, None) or json.loads(json.dumps(DEFAULT_POLICY))
    for c in CATEGORIES:
        p.setdefault("categories", {}).setdefault(c, {"block": c in DEFAULT_BLOCK})
    p["categories"]["S4"]["block"] = True
    p.setdefault("guard", DEFAULT_POLICY["guard"].copy())
    p.setdefault("tripwires", {"enabled": True, "extra_patterns": []})
    return p


def installed_models() -> list[dict]:
    st, j = http("GET", OLLAMA + "/api/tags", timeout=10)
    models = j.get("models", []) if isinstance(j, dict) else []
    st2, ps = http("GET", OLLAMA + "/api/ps", timeout=10)
    loaded = {m.get("name"): m for m in (ps.get("models", []) if isinstance(ps, dict) else [])}
    for m in models:
        m["loaded"] = m.get("name") in loaded
        m["vram"] = loaded.get(m.get("name"), {}).get("size_vram", 0)
        m["is_guard"] = "guard" in (m.get("name") or "").lower()
    return sorted(models, key=lambda m: m.get("name", ""))


def exposed_models() -> list[dict]:
    st, j = litellm("GET", "/model/info")
    return j.get("data", []) if isinstance(j, dict) else []


def current_domain() -> str | None:
    try:
        with open(DOMAIN_FILE, encoding="utf-8") as f:
            for line in f:
                m = re.match(r"^([a-z0-9.-]+) \{$", line.strip())
                if m:
                    return m.group(1)
    except FileNotFoundError:
        pass
    return None


def caddy_reload() -> tuple[bool, str]:
    try:
        with open(CADDYFILE, "rb") as f:
            body = f.read()
    except OSError as e:
        return False, f"cannot read Caddyfile: {e}"
    req = urllib.request.Request(f"{CADDY_ADMIN}/load", data=body, method="POST",
                                 headers={"Content-Type": "text/caddyfile", "Origin": "http://127.0.0.1:2019"})
    try:
        with urllib.request.urlopen(req, timeout=20) as r:
            return True, f"caddy reloaded ({r.status})"
    except urllib.error.HTTPError as e:
        return False, f"caddy rejected config: {e.read().decode(errors='replace')[:400]}"
    except Exception as e:  # noqa: BLE001
        return False, f"caddy admin unreachable: {e}"


def probe_cert(host, sni=None, port=443) -> dict:
    ctx = ssl.create_default_context(); ctx.check_hostname = False; ctx.verify_mode = ssl.CERT_NONE
    try:
        with socket.create_connection((host, port), timeout=5) as s, ctx.wrap_socket(s, server_hostname=sni or host) as tls:
            pem = ssl.DER_cert_to_PEM_cert(tls.getpeercert(binary_form=True))
    except Exception as e:  # noqa: BLE001
        return {"host": sni or host, "error": str(e)}
    import tempfile
    with tempfile.NamedTemporaryFile("w", suffix=".pem", delete=False) as f:
        f.write(pem); path = f.name
    try:
        d = ssl._ssl._test_decode_cert(path)  # type: ignore[attr-defined]
    finally:
        os.unlink(path)
    exp = datetime.strptime(d["notAfter"], "%b %d %H:%M:%S %Y %Z").replace(tzinfo=timezone.utc)
    return {"host": sni or host, "issuer": dict(x[0] for x in d.get("issuer", ())).get("commonName", "?"),
            "san": [v for k, v in d.get("subjectAltName", ()) if k == "DNS"], "not_after": d["notAfter"],
            "days": round((exp - datetime.now(timezone.utc)).total_seconds() / 86400, 1)}


def service_status() -> list[dict]:
    checks = [
        ("Caddy (gateway)", CADDY_ADMIN + "/config/", "edge"),
        ("Open WebUI", "http://openwebui:8080/health", "edge"),
        ("LiteLLM (API + VetoGuard)", LITELLM + "/health/liveliness", "edge/backend"),
        ("Ollama (inference)", OLLAMA + "/api/version", "backend"),
        ("modeld (model pulls)", MODELD + "/api/version", "mgmt"),
    ]
    if GRAFANA_ENABLED:
        checks.append(("Grafana", "http://grafana:3000/api/health", "edge/monitoring"))
    out = []
    for name, url, net in checks:
        st, _ = http("GET", url, timeout=4)
        out.append({"name": name, "net": net, "up": 200 <= st < 400, "code": st})
    for name, note in (("Fish Speech (TTS)", "apps profile — not started"), ("ComfyUI", "apps profile — 503 at edge until safety gate")):
        out.append({"name": name, "net": "apps", "up": None, "code": note})
    return out


def pull_job(model: str) -> str:
    jid = secrets.token_hex(4)
    with JOBS_LOCK:
        JOBS[jid] = {"model": model, "status": "starting", "completed": 0, "total": 0, "started": now(), "done": False}
    def run():
        req = urllib.request.Request(MODELD + "/api/pull", data=json.dumps({"name": model, "stream": True}).encode(),
                                     headers={"Content-Type": "application/json"}, method="POST")
        try:
            with urllib.request.urlopen(req, timeout=3600) as r:
                for line in r:
                    try:
                        d = json.loads(line)
                    except ValueError:
                        continue
                    with JOBS_LOCK:
                        JOBS[jid].update({"status": d.get("status", ""), "completed": d.get("completed", JOBS[jid]["completed"]),
                                          "total": d.get("total", JOBS[jid]["total"])})
                        if d.get("error"):
                            JOBS[jid].update({"status": "error: " + d["error"], "done": True})
                            return
            with JOBS_LOCK:
                JOBS[jid].update({"status": "complete", "done": True})
            audit("model_pull_complete", model=model)
        except Exception as e:  # noqa: BLE001
            with JOBS_LOCK:
                JOBS[jid].update({"status": f"error: {e}", "done": True})
            audit("model_pull_failed", model=model, error=str(e)[:200])
    threading.Thread(target=run, daemon=True).start()
    audit("model_pull_started", model=model, job=jid)
    return jid


# ---------------------------------------------------------------- HTML ---------------------
CSS = """
:root{--bg:#171717;--side:#0d0d0d;--card:#1f1f1f;--line:#2e2e2e;--fg:#ececec;--mut:#9a9a9a;--ok:#22c55e;--warn:#f59e0b;--bad:#ef4444;--acc:#ececec}
*{box-sizing:border-box}html,body{height:100%}body{margin:0;background:var(--bg);color:var(--fg);font:14px/1.5 -apple-system,Inter,"Segoe UI",system-ui,sans-serif}
a{color:inherit}.wrap{display:flex;height:100vh;height:100dvh;overflow:hidden}
nav{width:232px;flex:none;background:var(--side);border-right:1px solid var(--line);padding:18px 12px;overflow-y:auto;overscroll-behavior:contain;scrollbar-width:none;-ms-overflow-style:none;-webkit-overflow-scrolling:touch}nav::-webkit-scrollbar{display:none}
nav .brand{font-weight:600;font-size:16px;padding:6px 10px 16px;letter-spacing:.2px}
nav details{margin:2px 0}nav summary{list-style:none;cursor:pointer;color:var(--mut);font-size:11px;text-transform:uppercase;letter-spacing:.08em;padding:10px 10px 4px;user-select:none;display:flex;justify-content:space-between;align-items:center}
nav summary::-webkit-details-marker{display:none}nav summary::after{content:"+";font-size:13px;color:#666}nav details[open] summary::after{content:"–"}
nav details[open] summary{color:#ddd}
nav a{display:block;padding:7px 10px 7px 14px;border-radius:8px;text-decoration:none;color:#cfcfcf}
nav a:hover{background:#1a1a1a}nav a.on{background:#262626;color:#fff}
main{flex:1;min-width:0;overflow-y:auto;padding:26px 34px}main>.inner{max-width:1180px}
h1{font-size:20px;font-weight:600;margin:0 0 4px}h2{font-size:15px;font-weight:600;margin:22px 0 8px}
.sub{color:var(--mut);margin:0 0 18px}.card{background:var(--card);border:1px solid var(--line);border-radius:12px;padding:16px 18px;margin:12px 0}
.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(250px,1fr));gap:12px}
table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:8px 10px;border-bottom:1px solid var(--line);vertical-align:top}th{color:var(--mut);font-weight:500;font-size:12px}
.card table{display:block;overflow-x:auto}
.tag{display:inline-block;font-size:11px;padding:2px 8px;border-radius:999px;background:#2a2a2a;color:#ddd}.ok{color:var(--ok)}.warn{color:var(--warn)}.bad{color:var(--bad)}.mut{color:var(--mut)}
input,select,textarea{background:#111;color:var(--fg);border:1px solid #3a3a3a;border-radius:8px;padding:8px 10px;font:inherit;width:100%;max-width:520px}
textarea{min-height:90px;font-family:ui-monospace,Menlo,monospace;font-size:12px}
button{background:var(--acc);color:#111;border:0;border-radius:8px;padding:8px 14px;font:inherit;font-weight:600;cursor:pointer}
button.ghost{background:#2a2a2a;color:#eee}button.danger{background:var(--bad);color:#fff}
form.inline{display:inline}label{display:block;margin:10px 0 4px;color:#ccc}.row{display:flex;gap:10px;flex-wrap:wrap;align-items:end}
pre{background:#0d0d0d;border:1px solid var(--line);border-radius:10px;padding:12px;overflow:auto;font-size:12px;max-height:520px}
.msg{padding:10px 14px;border-radius:10px;margin:0 0 14px;background:#1c2a1c;border:1px solid #2f5a2f}.msg.bad{background:#2a1c1c;border-color:#5a2f2f}
.pager{display:flex;gap:18px;flex-wrap:wrap;align-items:center;justify-content:space-between;margin:8px 0 2px;font-size:12px;color:#bbb}.pager a{padding:2px 7px;border-radius:6px;background:#2a2a2a;text-decoration:none;margin:0 1px}.pager a.on{background:#3a3a3a;color:#fff}
.lock{opacity:.6}.key{font-family:ui-monospace,monospace;background:#0d0d0d;padding:6px 10px;border-radius:8px;display:inline-block;user-select:all;word-break:break-all}
@media (max-width:760px){.wrap{flex-direction:column;height:auto;overflow:visible}nav{width:auto;border-right:0;border-bottom:1px solid var(--line);overflow:visible}main{overflow:visible;padding:18px 16px}}
"""


def page(section, sub, title, subtitle, body, msg="", ok=True):
    nav = ['<div class="brand">Aegis</div>']
    for sid, sname, subs in NAV:
        links = "".join(f'<a class="{"on" if (sid, ssid) == (section, sub) else ""}" href="/hub/{sid}/{ssid}">{esc(ssname)}</a>' for ssid, ssname in subs)
        nav.append(f'<details{" open" if sid == section else ""}><summary>{esc(sname)}</summary>{links}</details>')
    apps = '<a href="/">Open WebUI ↗</a>' + ('<a href="/grafana/">Grafana ↗</a>' if GRAFANA_ENABLED else '')
    nav.append(f'<details><summary>Apps</summary>{apps}</details>')
    m = f'<div class="msg{"" if ok else " bad"}">{esc(msg)}</div>' if msg else ""
    return f"""<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Aegis Hub — {esc(title)}</title><style>{CSS}</style></head><body><div class="wrap"><nav>{''.join(nav)}</nav>
<main><div class="inner"><h1>{esc(title)}</h1><p class="sub">{esc(subtitle)}</p>{m}{body}</div></main></div></body></html>"""


def csrf_field():
    return f'<input type="hidden" name="csrf" value="{CSRF}">'


# ---------------------------------------------------------------- pages --------------------
def p_dashboard(msg="", ok=True):
    pol = policy(); blocked = sorted(c for c, v in pol["categories"].items() if v.get("block"))
    svc = service_status()
    tiles = "".join(
        f'<div class="card"><b>{esc(s["name"])}</b> <span class="tag">{esc(s["net"])}</span><div class="{"ok" if s["up"] else ("mut" if s["up"] is None else "bad")}">'
        f'{"up" if s["up"] else ("—" if s["up"] is None else "DOWN")} <span class="mut">{esc(s["code"])}</span></div></div>' for s in svc)
    models = installed_models(); loaded = [m for m in models if m["loaded"]]
    vram = ", ".join(f'{esc(m["name"])} ({m["vram"] / 2**30:.1f} GiB VRAM)' for m in loaded) or "nothing resident"
    if loaded and all(m["vram"] == 0 for m in loaded):
        vram += ' <span class="bad">— resident models have 0 VRAM: the inference container has lost its GPUs (NVML error). Console: <code>docker compose restart ollama</code>.</span>'
        if msg == "":
            msg, ok = "GPU residency lost — see Safety posture. Inference is running on CPU.", False
    certs = [probe_cert(LAN_IP)] + ([probe_cert(LAN_IP, current_domain())] if current_domain() else [])
    certrows = "".join(f'<tr><td>{esc(c["host"])}</td><td>{esc(c.get("issuer", c.get("error")))}</td><td class="{"warn" if c.get("days", 99) < 14 else "ok"}">{c.get("days", "—")}</td></tr>' for c in certs)
    events = tail_jsonl(VETO_AUDIT, 8)
    evrows = "".join(f'<tr><td class="mut">{esc(e.get("ts", "")[:19])}</td><td>{esc(e.get("stage"))}</td><td>{esc(e.get("reason"))}</td><td>{esc(e.get("detail", ""))[:60]}</td><td>{esc(e.get("key_alias"))}</td></tr>' for e in events) or '<tr><td colspan="5" class="mut">no vetoes recorded</td></tr>'
    body = f"""<div class="grid">{tiles}</div>
<div class="card"><h2 style="margin-top:0">Safety posture</h2>Guard model <span class="tag">{esc(pol["guard"]["model"])}</span> · blocking {len(blocked)} categories: {esc(", ".join(blocked))} · tripwires {"on" if pol["tripwires"].get("enabled") else "OFF"} · <b>fail-closed</b> · streaming buffered
<div class="mut" style="margin-top:6px">Resident in VRAM: {vram}</div></div>
<div class="card"><h2 style="margin-top:0">Certificates</h2><table><tr><th>Host</th><th>Issuer</th><th>Days left</th></tr>{certrows}</table></div>
<div class="card"><h2 style="margin-top:0">Recent vetoes</h2><table><tr><th>Time</th><th>Stage</th><th>Reason</th><th>Detail</th><th>Key</th></tr>{evrows}</table></div>"""
    return page("overview", "dashboard", "Dashboard", "Live state of the platform. Nothing here is editable.", body, msg, ok)


def p_services():
    svc, sctl = paginate(service_status(), "s")
    rows = "".join(f'<tr><td>{esc(s["name"])}</td><td><span class="tag">{esc(s["net"])}</span></td><td class="{"ok" if s["up"] else ("mut" if s["up"] is None else "bad")}">{"up" if s["up"] else ("not started" if s["up"] is None else "DOWN")}</td><td class="mut">{esc(s["code"])}</td></tr>' for s in svc)
    body = f'<div class="card">{sctl}<table><tr><th>Service</th><th>Network</th><th>State</th><th>Detail</th></tr>{rows}</table></div><p class="mut">Starting/stopping services and changing what they may talk to is an isolation-layer change: console only.</p>'
    return page("overview", "services", "Services", "Health of every container, by network.", body)


def p_policy(msg="", ok=True):
    pol = policy(); guards = [m["name"] for m in installed_models() if m["is_guard"]] or [pol["guard"]["model"]]
    if pol["guard"]["model"] not in guards:
        guards.append(pol["guard"]["model"])
    opts = "".join(f'<option value="{esc(g)}"{" selected" if g == pol["guard"]["model"] else ""}>{esc(g)}</option>' for g in guards)
    rows = ""
    for c, (name, kind) in CATEGORIES.items():
        b = pol["categories"][c]["block"]; locked = c == "S4"
        rows += f'<tr class="{"lock" if locked else ""}"><td><input type="checkbox" name="block_{c}" {"checked" if b else ""} {"disabled" if locked else ""} style="width:auto"></td><td>{c}</td><td>{esc(name)}</td><td><span class="tag">{esc(kind)}</span></td><td class="mut">{"always blocked — cannot be changed" if locked else ""}</td></tr>'
    extra = "\n".join(pol["tripwires"].get("extra_patterns", []))
    body = f"""<form method="post" action="/hub/api/policy">{csrf_field()}
<div class="card"><h2 style="margin-top:0">Classifier (Llama Guard 3)</h2>
<label>Guard model (installed models containing "guard")</label><select name="guard_model">{opts}</select>
<div class="mut" style="margin-top:6px">The classifier runs on every request and every response (streaming buffered). It cannot be disabled. If it is unreachable, requests are refused. Changing the model takes effect on the next request; the first call loads it.</div></div>
<div class="card"><h2 style="margin-top:0">Blocked categories</h2><table><tr><th>Block</th><th>Code</th><th>Category</th><th>Class</th><th></th></tr>{rows}</table>
<div class="mut">Policy intent: illegal and protected-class content never passes; adult content may. Unchecking an "illegal" class is allowed but audited and alerted.</div></div>
<div class="card"><h2 style="margin-top:0">Lexical tripwires</h2><label><input type="checkbox" name="tripwires" {"checked" if pol["tripwires"].get("enabled", True) else ""} style="width:auto"> Enabled (built-in lists for sentinel / CSAM terms / malware intent)</label>
<label>Extra patterns — one Python regex per line, matched case-insensitively against normalised text</label><textarea name="extra">{esc(extra)}</textarea></div>
<p class="mut">Last change: {esc(pol.get("updated") or "never")} by {esc(pol.get("updated_by") or "—")}. Saving is logged and alerted.</p>
<button type="submit">Save policy</button></form>"""
    return page("safety", "policy", "VetoGuard policy", "What the safety gate blocks. Administrator only; every change is audited.", body, msg, ok)


def p_audit():
    veto, vctl = paginate(tail_jsonl(VETO_AUDIT, 5000), "v")
    hub, hctl = paginate(tail_jsonl(HUB_AUDIT, 5000), "h")
    vrows = "".join(f'<tr><td class="mut">{esc(e.get("ts", "")[:19])}</td><td>{esc(e.get("stage"))}</td><td>{esc(e.get("reason"))}</td><td>{esc(e.get("detail", ""))[:80]}</td><td>{esc(e.get("model"))}</td><td>{esc(e.get("key_alias"))}</td></tr>' for e in veto) or '<tr><td colspan="6" class="mut">none</td></tr>'
    hrows = "".join(f'<tr><td class="mut">{esc(e.get("ts", "")[:19])}</td><td>{esc(e.get("event"))}</td><td>{esc(", ".join(f"{k}={v}" for k, v in e.items() if k not in ("ts", "event", "actor")))[:120]}</td></tr>' for e in hub) or '<tr><td colspan="3" class="mut">none</td></tr>'
    body = f'<div class="card"><h2 style="margin-top:0">Vetoes</h2>{vctl}<table><tr><th>Time</th><th>Stage</th><th>Reason</th><th>Detail</th><th>Model</th><th>Key</th></tr>{vrows}</table>{vctl}</div><div class="card"><h2 style="margin-top:0">Admin actions</h2>{hctl}<table><tr><th>Time</th><th>Event</th><th>Fields</th></tr>{hrows}</table>{hctl}</div><p class="mut">Logs never contain message content. Files: proxy/audit/veto-audit.jsonl, proxy/audit/hub-audit.jsonl (root-only on the host).</p>'
    return page("safety", "audit", "Audit log", "Every veto and every administrative action.", body)


def p_alerts(msg="", ok=True):
    body = f"""<form method="post" action="/hub/api/alerts">{csrf_field()}<div class="card"><label>Webhook URL (Discord, Slack, or any endpoint accepting JSON POST)</label><input name="webhook" value="{esc(state().get("webhook", ""))}" placeholder="https://…">
<div class="mut" style="margin-top:6px">Every admin action and policy change is posted here. Leave blank to disable. Sent as {{"text","content"}} so Discord and Slack both render it.</div>
<div class="row" style="margin-top:12px"><button name="action" value="save">Save</button><button class="ghost" name="action" value="test">Send test</button></div></div></form>"""
    return page("safety", "alerts", "Alerts", "Where administrative and safety events are pushed.", body, msg, ok)


def p_installed(msg="", ok=True):
    exposed = {m.get("litellm_params", {}).get("model", "").replace("ollama/", ""): m.get("model_name") for m in exposed_models()}
    rows = ""
    models, mctl = paginate(installed_models(), "m")
    for m in models:
        n = m["name"]; size = m.get("size", 0) / 2**30
        exp = exposed.get(n) or exposed.get(n.replace(":latest", ""))
        act = '<span class="tag">guard model</span>' if m["is_guard"] else (
            f'<span class="tag ok">exposed as {esc(exp)}</span>' if exp else
            f'<form class="inline" method="post" action="/hub/api/models/expose">{csrf_field()}<input type="hidden" name="model" value="{esc(n)}"><input name="public" placeholder="public name" style="width:150px" value="{esc(n.split(":")[0].split("/")[-1])}"> <button class="ghost">Expose</button></form>')
        rm = "" if exp or m["loaded"] else f'<form class="inline" method="post" action="/hub/api/models/remove">{csrf_field()}<input type="hidden" name="model" value="{esc(n)}"><input type="hidden" name="confirm" value="{esc(n)}"><button class="danger">Remove</button></form>'
        rows += f'<tr><td>{esc(n)}</td><td>{size:.1f} GiB</td><td>{"<span class=ok>resident</span>" if m["loaded"] else "<span class=mut>on disk</span>"}</td><td>{act}</td><td>{rm}</td></tr>'
    body = f'<div class="card">{mctl}<table><tr><th>Model</th><th>Size</th><th>State</th><th>Exposure</th><th></th></tr>{rows or "<tr><td colspan=5 class=mut>none</td></tr>"}</table></div><p class="mut">"Expose" registers the model in LiteLLM under a public name so Open WebUI and API keys can use it — through VetoGuard. Guard models are never exposable. A model that is exposed or resident cannot be removed.</p>'
    return page("models", "installed", "Installed models", "What is in the shared model store, and what apps can see.", body, msg, ok)


def p_pull(msg="", ok=True):
    with JOBS_LOCK:
        jobs = sorted(JOBS.items(), key=lambda kv: kv[1]["started"], reverse=True)
    jobs, jctl = paginate(jobs, "j", 10)
    rows = "".join(f'<tr><td>{esc(j["model"])}</td><td>{esc(j["status"])}</td><td>{(j["completed"] / j["total"] * 100) if j["total"] else 0:.0f}%</td><td class="mut">{esc(j["started"][:19])}</td></tr>' for _, j in jobs) or '<tr><td colspan="4" class="mut">no pulls yet</td></tr>'
    body = f"""<form method="post" action="/hub/api/models/pull">{csrf_field()}<div class="card"><label>Model to pull (Ollama library name, e.g. <code>qwen2.5:14b</code>, <code>llama-guard3:8b</code>)</label><div class="row"><input name="model" placeholder="name:tag" required pattern="[a-z0-9][a-z0-9._/:-]*"><button>Pull</button></div>
<div class="mut" style="margin-top:6px">Pulls run through <b>modeld</b>, the only container with both internet access and the model store. The inference engine never fetches anything itself.</div></div></form>
<div class="card"><h2 style="margin-top:0">Jobs</h2>{jctl}<table><tr><th>Model</th><th>Status</th><th>Progress</th><th>Started</th></tr>{rows}</table><p class="mut">Refresh the page for progress.</p></div>"""
    return page("models", "pull", "Pull a model", "Download into the shared store, behind the scenes, for every app on the box.", body, msg, ok)


def p_exposed(msg="", ok=True):
    rows = ""
    ex, ectl = paginate(exposed_models(), "e")
    for m in ex:
        mid = str(m.get("model_info", {}).get("id", "")); pub = m.get("model_name"); up = m.get("litellm_params", {}).get("model")
        src = "hub" if len(mid) >= 8 and "-" in mid else "config.yaml (console)"
        rm = f'<form class="inline" method="post" action="/hub/api/models/unexpose">{csrf_field()}<input type="hidden" name="id" value="{esc(mid)}"><input type="hidden" name="public" value="{esc(pub)}"><button class="danger">Unexpose</button></form>' if src == "hub" else '<span class="mut">console</span>'
        rows += f'<tr><td>{esc(pub)}</td><td>{esc(up)}</td><td>{esc(src)}</td><td>{rm}</td></tr>'
    body = f'<div class="card">{ectl}<table><tr><th>Public name</th><th>Upstream</th><th>Defined in</th><th></th></tr>{rows or "<tr><td colspan=4 class=mut>none</td></tr>"}</table></div><p class="mut">Public names are what API keys and Open WebUI address. Everything listed routes through VetoGuard.</p>'
    return page("models", "exposed", "Exposed to apps", "Models LiteLLM currently serves.", body, msg, ok)


def p_keys(msg="", ok=True, newkey=None):
    st, j = litellm("GET", "/key/list?return_full_object=true&page=1&size=100")
    keys = [k for k in (j.get("keys", []) if isinstance(j, dict) else []) if k.get("key_alias")]
    keys, kctl = paginate(keys, "k")
    rows = "".join(f'<tr><td>{esc(k.get("key_alias"))}</td><td>{esc(", ".join(k.get("models") or []) or "all exposed")}</td><td>{esc(k.get("rpm_limit"))}/{esc(k.get("tpm_limit"))}</td><td class="mut">{esc((k.get("created_at") or "")[:19])}</td><td><form class="inline" method="post" action="/hub/api/keys/revoke">{csrf_field()}<input type="hidden" name="alias" value="{esc(k.get("key_alias"))}"><button class="danger">Revoke</button></form></td></tr>' for k in keys if k.get("key_alias")) or '<tr><td colspan="5" class="mut">none</td></tr>'
    pubs = [m.get("model_name") for m in exposed_models()]
    opts = "".join(f'<option value="{esc(p)}">{esc(p)}</option>' for p in pubs)
    banner = f'<div class="card"><b>New key — shown once, store it now:</b><br><span class="key">{esc(newkey)}</span></div>' if newkey else ""
    body = f"""{banner}<div class="card">{kctl}<table><tr><th>Alias</th><th>Models</th><th>rpm/tpm</th><th>Created</th><th></th></tr>{rows}</table></div>
<form method="post" action="/hub/api/keys/mint">{csrf_field()}<div class="card"><h2 style="margin-top:0">Mint a key</h2>
<div class="row"><div><label>Alias (client name)</label><input name="alias" required pattern="[a-z0-9][a-z0-9._-]+" placeholder="home-assistant"></div>
<div><label>Models</label><select name="models" multiple size="3">{opts}</select></div>
<div><label>rpm</label><input name="rpm" type="number" value="60" min="1" style="width:100px"></div><div><label>tpm</label><input name="tpm" type="number" value="200000" min="1000" style="width:130px"></div>
<button>Mint</button></div><div class="mut" style="margin-top:6px">Keys are per client, model-scoped and rate-limited. The master key never leaves the console/hub.</div></div></form>"""
    return page("access", "keys", "API keys", "Credentials for other services using the OpenAI-compatible API at /v1.", body, msg, ok)


def p_certs():
    dom = current_domain(); certs = [probe_cert(LAN_IP)] + ([probe_cert(LAN_IP, dom)] if dom else [])
    rows = "".join(f'<tr><td>{esc(c["host"])}</td><td>{esc(c.get("issuer", ""))}</td><td>{esc(", ".join(c.get("san", [])))}</td><td>{esc(c.get("not_after", ""))}</td><td class="{"warn" if c.get("days", 99) < 14 else "ok"}">{c.get("days", "")}</td><td class="bad">{esc(c.get("error", ""))}</td></tr>' for c in certs)
    body = f'<div class="card"><table><tr><th>Host</th><th>Issuer</th><th>SANs</th><th>Expires</th><th>Days</th><th></th></tr>{rows}</table></div><p class="mut">Caddy renews automatically at two-thirds of lifetime. The internal CA root (caddy/data/caddy/pki/authorities/local/root.crt) can be installed on client devices to remove browser warnings for the LAN address.</p>'
    return page("gateway", "certs", "Certificates", "Live TLS state of every endpoint Caddy serves.", body)


def p_hostname(msg="", ok=True):
    dom = current_domain()
    body = f"""<form method="post" action="/hub/api/hostname">{csrf_field()}<div class="card"><h2 style="margin-top:0">Public hostname via Cloudflare DNS-01</h2>
<p class="mut">The box stays private. Caddy proves ownership by writing a TXT record with a scoped Cloudflare token, then obtains a Let's Encrypt certificate. No inbound ports. Your DNS A record should point at the LAN IP with the proxy <b>off</b> (DNS only).</p>
<label>Hostname</label><input name="hostname" value="{esc(dom or "")}" placeholder="ai.example.com" pattern="[a-z0-9.-]+">
<label>Cloudflare API token (Zone → DNS → Edit, scoped to the zone). Leave blank to keep the stored one.</label><input name="token" type="password" autocomplete="off">
<div class="row" style="margin-top:12px"><button name="action" value="apply">Apply</button><button class="danger" name="action" value="remove" formnovalidate>Remove hostname</button></div>
<div class="mut" style="margin-top:8px">Current: <b>{esc(dom or "none")}</b>. The token is stored only in the root-only site file Caddy reads; it is never shown again.</div></div></form>"""
    return page("gateway", "hostname", "Public hostname", "The one piece of Caddy configuration the hub may write.", body, msg, ok)


def p_isolation():
    try:
        cf = open(CADDYFILE, encoding="utf-8").read()
    except OSError as e:
        cf = f"(unreadable: {e})"
    try:
        comp = open(COMPOSE_VIEW, encoding="utf-8").read()
    except OSError as e:
        comp = f"(unreadable: {e})"
    nets = "\n".join(l for l in comp.splitlines() if re.match(r"^(networks:|  [a-z0-9_-]+:$|    networks:|    network_mode|      internal:|    ports:)", l) or re.match(r"^    - \"\d", l))
    body = f'<p class="mut">This is the isolation layer. It is shown so you can verify it; changing it requires the console and root.</p><div class="card"><h2 style="margin-top:0">caddy/Caddyfile</h2><pre>{esc(cf)}</pre></div><div class="card"><h2 style="margin-top:0">docker-compose.yml — network wiring</h2><pre>{esc(nets)}</pre><details><summary class="mut">full compose file</summary><pre>{esc(comp)}</pre></details></div>'
    return page("gateway", "isolation", "Isolation (read-only)", "Interconnects, routes, auth and capabilities — view only.", body)


# ---------------------------------------------------------------- actions ------------------
def act_policy(form):
    pol = policy(); before = {c: v["block"] for c, v in pol["categories"].items()}
    gm = form.get("guard_model", pol["guard"]["model"])
    if not MODEL_RE.match(gm) or "guard" not in gm.lower():
        return p_policy("Guard model must be an installed model whose name contains 'guard'.", False)
    for c in CATEGORIES:
        pol["categories"][c]["block"] = (f"block_{c}" in form) or c == "S4"
    extra = [l.strip() for l in form.get("extra", "").splitlines() if l.strip()]
    for pat in extra:
        try:
            re.compile(pat)
        except re.error as e:
            return p_policy(f"Invalid regex {pat!r}: {e}", False)
    pol["guard"]["model"] = gm
    pol["tripwires"] = {"enabled": "tripwires" in form, "extra_patterns": extra}
    pol["updated"], pol["updated_by"] = now(), "admin"
    save_json(POLICY_FILE, pol)
    changed = [f"{c}:{'block' if pol['categories'][c]['block'] else 'allow'}" for c in CATEGORIES if before[c] != pol["categories"][c]["block"]]
    audit("policy_saved", guard_model=gm, changed=",".join(changed) or "none", tripwires=pol["tripwires"]["enabled"], extra_patterns=len(extra))
    return p_policy("Policy saved. LiteLLM picks it up on the next request (no restart).")


def act_alerts(form):
    s = state()
    if form.get("action") == "test":
        alert("test alert from Aegis Hub"); return p_alerts("Test sent (if a webhook is configured).")
    url = form.get("webhook", "").strip()
    if url and not url.startswith("https://"):
        return p_alerts("Webhook must be an https:// URL.", False)
    s["webhook"] = url; save_json(STATE_FILE, s); audit("alerts_webhook_set", configured=bool(url))
    return p_alerts("Saved.")


def act_pull(form):
    m = form.get("model", "").strip().lower()
    if not MODEL_RE.match(m):
        return p_pull("Invalid model name.", False)
    pull_job(m); return p_pull(f"Pull started for {m}.")


def act_expose(form):
    m, pub = form.get("model", "").strip(), form.get("public", "").strip().lower()
    if not MODEL_RE.match(m) or "guard" in m.lower():
        return p_installed("Guard models cannot be exposed.", False)
    if not ALIAS_RE.match(pub):
        return p_installed("Public name must be lowercase letters, digits, dot, dash, underscore.", False)
    st, j = litellm("POST", "/model/new", {"model_name": pub, "litellm_params": {"model": f"ollama/{m}", "api_base": OLLAMA}})
    ok = st == 200; audit("model_exposed" if ok else "model_expose_failed", model=m, public=pub, status=st)
    return p_installed(f"Exposed {m} as {pub}." if ok else f"LiteLLM refused ({st}): {str(j)[:200]}", ok)


def act_unexpose(form):
    mid, pub = form.get("id", ""), form.get("public", "")
    st, j = litellm("POST", "/model/delete", {"id": mid}); ok = st == 200
    audit("model_unexposed" if ok else "model_unexpose_failed", public=pub, status=st)
    return p_exposed(f"Unexposed {pub}." if ok else f"LiteLLM refused ({st}).", ok)


def act_remove(form):
    m = form.get("model", "")
    if form.get("confirm") != m or not MODEL_RE.match(m):
        return p_installed("Confirmation mismatch.", False)
    st, j = http("DELETE", OLLAMA + "/api/delete", {"name": m}, timeout=60); ok = st == 200
    audit("model_removed" if ok else "model_remove_failed", model=m, status=st)
    return p_installed(f"Removed {m}." if ok else f"Ollama refused ({st}): {str(j)[:200]}", ok)


def act_mint(form):
    alias = form.get("alias", "").strip().lower(); models = form.getlist("models")
    try:
        rpm, tpm = int(form.get("rpm", 60)), int(form.get("tpm", 200000))
    except ValueError:
        return p_keys("rpm/tpm must be integers.", False)
    if not ALIAS_RE.match(alias):
        return p_keys("Alias must be lowercase letters, digits, dot, dash, underscore.", False)
    st, j = litellm("POST", "/key/generate", {"key_alias": alias, "models": models, "rpm_limit": rpm, "tpm_limit": tpm, "metadata": {"minted_by": "hub", "at": now()}})
    ok = st == 200 and isinstance(j, dict) and j.get("key")
    audit("key_minted" if ok else "key_mint_failed", alias=alias, models=",".join(models), rpm=rpm, tpm=tpm, status=st)
    return p_keys(f"Key minted for {alias}." if ok else f"LiteLLM refused ({st}): {str(j)[:200]}", bool(ok), newkey=j.get("key") if ok else None)


def act_revoke(form):
    alias = form.get("alias", "")
    st, j = litellm("POST", "/key/delete", {"key_aliases": [alias]}); ok = st == 200
    audit("key_revoked" if ok else "key_revoke_failed", alias=alias, status=st)
    return p_keys(f"Revoked {alias}." if ok else f"LiteLLM refused ({st}).", ok)


def act_hostname(form):
    if form.get("action") == "remove":
        try:
            os.unlink(DOMAIN_FILE)
        except FileNotFoundError:
            pass
        ok, m = caddy_reload(); audit("hostname_removed", ok=ok, detail=m)
        return p_hostname(f"Removed. {m}", ok)
    host = form.get("hostname", "").strip().lower(); token = form.get("token", "").strip()
    if not HOSTNAME_RE.match(host):
        audit("hostname_rejected", hostname=host); return p_hostname("Rejected: not a valid public DNS name.", False)
    if not token:
        try:
            cur = open(DOMAIN_FILE, encoding="utf-8").read()
            token = re.search(r"dns cloudflare (\S+)", cur).group(1)
        except Exception:  # noqa: BLE001
            return p_hostname("A Cloudflare API token is required the first time.", False)
    if not CF_TOKEN_RE.match(token):
        return p_hostname("Rejected: token format not recognised.", False)
    prev = open(DOMAIN_FILE, encoding="utf-8").read() if os.path.exists(DOMAIN_FILE) else None
    tmp = DOMAIN_FILE + ".tmp"
    with open(tmp, "w", encoding="utf-8") as f:
        f.write(DOMAIN_TEMPLATE.format(ts=now(), hostname=host, token=token))
    os.chmod(tmp, 0o600); os.replace(tmp, DOMAIN_FILE)
    ok, m = caddy_reload()
    if not ok:
        if prev is None:
            os.unlink(DOMAIN_FILE)
        else:
            open(DOMAIN_FILE, "w", encoding="utf-8").write(prev)
        caddy_reload()
    audit("hostname_applied" if ok else "hostname_apply_failed", hostname=host, detail=m)
    s = state(); s["hostname"] = host if ok else s.get("hostname", ""); save_json(STATE_FILE, s)
    return p_hostname(f"Applied {host}. Caddy will obtain the certificate via DNS-01 within a minute or two; check Certificates. {m}" if ok else f"Failed and rolled back: {m}", ok)



def p_password(msg="", ok=True):
    body = f"""<form method="post" action="/hub/api/password">{csrf_field()}<div class="card"><h2 style="margin-top:0">Change the administrator password</h2>
<p class="mut">This is the credential Caddy checks before anything reaches the hub. Rotating it writes a new bcrypt hash to the root-only auth file and reloads Caddy; your browser will prompt again.</p>
<label>Current password</label><input name="current" type="password" autocomplete="current-password" required>
<label>New password</label><input name="new" type="password" autocomplete="new-password" required minlength="14">
<label>Confirm new password</label><input name="confirm" type="password" autocomplete="new-password" required minlength="14">
<div class="mut" style="margin-top:8px">Policy: at least 14 characters; at least three of: lowercase, uppercase, digit, symbol; no spaces; must not contain "admin", "aegis" or "password". bcrypt cost 14.</div>
<div class="row" style="margin-top:12px"><button>Change password</button></div></div></form>"""
    return page("access", "password", "Admin password", "Rotate the hub administrator credential without the console.", body, msg, ok)


def _password_policy(pw: str) -> str | None:
    if len(pw) < 14: return "too short (minimum 14 characters)"
    if len(pw) > 128: return "too long (maximum 128)"
    if any(ch.isspace() for ch in pw): return "must not contain spaces"
    classes = sum([any(c.islower() for c in pw), any(c.isupper() for c in pw), any(c.isdigit() for c in pw), any(not c.isalnum() for c in pw)])
    if classes < 3: return "needs at least three of: lowercase, uppercase, digit, symbol"
    low = pw.lower()
    if any(w in low for w in ("admin", "aegis", "password", "qwerty", "123456")): return "contains a forbidden word"
    return None


def _current_hash() -> str | None:
    try:
        m = re.search(r"^\s*admin\s+(\S+)\s*$", open(HUB_AUTH_FILE, encoding="utf-8").read(), re.M)
        return m.group(1) if m else None
    except OSError:
        return None


def act_password(form):
    import bcrypt
    cur, new, conf = form.get("current", ""), form.get("new", ""), form.get("confirm", "")
    h = _current_hash()
    if not h or not bcrypt.checkpw(cur.encode(), h.encode()):
        audit("admin_password_change_rejected", reason="current password incorrect")
        return p_password("Current password is incorrect.", False)
    if new != conf:
        return p_password("New password and confirmation do not match.", False)
    why = _password_policy(new)
    if why:
        return p_password(f"Rejected: {why}.", False)
    if bcrypt.checkpw(new.encode(), h.encode()):
        return p_password("New password must differ from the current one.", False)
    newh = bcrypt.hashpw(new.encode(), bcrypt.gensalt(rounds=14)).decode()
    prev = open(HUB_AUTH_FILE, encoding="utf-8").read()
    tmp = HUB_AUTH_FILE + ".tmp"
    with open(tmp, "w", encoding="utf-8") as f:
        f.write(f"# Hub administrator credential. Managed from /hub (Access -> Admin password). bcrypt. Rotated {now()}\nbasic_auth {{\n    admin {newh}\n}}\n")
    os.chmod(tmp, 0o600); os.replace(tmp, HUB_AUTH_FILE)
    ok, m = caddy_reload()
    if not ok:
        open(HUB_AUTH_FILE, "w", encoding="utf-8").write(prev); caddy_reload()
        audit("admin_password_change_failed", detail=m)
        return p_password(f"Caddy refused the new credential; previous password kept. {m}", False)
    audit("admin_password_changed", detail=m)
    return p_password("Password changed. Caddy reloaded — your browser will ask for the new password on the next request. HUB_ADMIN_PASSWORD in .env is now stale; this file is the source of truth.")


ACTIONS = {"/hub/api/policy": act_policy, "/hub/api/alerts": act_alerts, "/hub/api/models/pull": act_pull,
           "/hub/api/models/expose": act_expose, "/hub/api/models/unexpose": act_unexpose, "/hub/api/models/remove": act_remove,
           "/hub/api/keys/mint": act_mint, "/hub/api/keys/revoke": act_revoke, "/hub/api/password": act_password, "/hub/api/hostname": act_hostname}
PAGES = {("overview", "dashboard"): p_dashboard, ("overview", "services"): p_services, ("safety", "policy"): p_policy,
         ("safety", "audit"): p_audit, ("safety", "alerts"): p_alerts, ("models", "installed"): p_installed,
         ("models", "pull"): p_pull, ("models", "exposed"): p_exposed, ("access", "keys"): p_keys, ("access", "password"): p_password,
         ("gateway", "certs"): p_certs, ("gateway", "hostname"): p_hostname, ("gateway", "isolation"): p_isolation}


class Form(dict):
    def __init__(self, qs):
        self.raw = urllib.parse.parse_qs(qs, keep_blank_values=True)
        super().__init__({k: v[0] for k, v in self.raw.items()})

    def getlist(self, k):
        return self.raw.get(k, [])


class Handler(BaseHTTPRequestHandler):
    server_version = "AegisHub/2"

    def log_message(self, *a):  # Caddy keeps the access log
        pass

    def _send(self, code, body, ctype="text/html; charset=utf-8"):
        data = body.encode()
        self.send_response(code)
        self.send_header("Content-Type", ctype); self.send_header("Content-Length", str(len(data)))
        self.send_header("Cache-Control", "no-store"); self.send_header("X-Frame-Options", "DENY")
        self.end_headers(); self.wfile.write(data)

    def do_GET(self):
        u = urllib.parse.urlparse(self.path)
        REQ.q, REQ.path = urllib.parse.parse_qs(u.query), u.path
        p = u.path.rstrip("/")
        if p == "/hub":
            return self._send(200, p_dashboard())
        if p == "/hub/api/status":
            dom = current_domain()
            return self._send(200, json.dumps({"services": service_status(), "lan": probe_cert(LAN_IP), "domain": dom,
                                               "public": probe_cert(LAN_IP, dom) if dom else None, "policy": policy()}, indent=1), "application/json")
        if p == "/hub/api/jobs":
            with JOBS_LOCK:
                return self._send(200, json.dumps(JOBS), "application/json")
        parts = p.split("/")
        if len(parts) == 4 and (parts[2], parts[3]) in PAGES:
            return self._send(200, PAGES[(parts[2], parts[3])]())
        self._send(404, "not found", "text/plain")

    def do_POST(self):
        REQ.q, REQ.path = {}, urllib.parse.urlparse(self.path).path
        p = urllib.parse.urlparse(self.path).path
        n = int(self.headers.get("Content-Length", "0"))
        form = Form(self.rfile.read(min(n, 65536)).decode())
        if form.get("csrf") != CSRF:
            return self._send(403, "invalid or expired form token — reload the page", "text/plain")
        fn = ACTIONS.get(p)
        if not fn:
            return self._send(404, "not found", "text/plain")
        try:
            self._send(200, fn(form))
        except Exception as e:  # noqa: BLE001
            audit("hub_error", path=p, error=str(e)[:200])
            self._send(500, p_dashboard(f"Action failed: {e}", False))


if __name__ == "__main__":
    os.makedirs(SITES_DIR, exist_ok=True); os.makedirs(os.path.dirname(STATE_FILE), exist_ok=True)
    if not os.path.exists(POLICY_FILE):
        save_json(POLICY_FILE, DEFAULT_POLICY)
    ThreadingHTTPServer(("127.0.0.1", 9000), Handler).serve_forever()
